### ISSUE TITLE
Won't activate - fatal error

### ISSUE THREAD

**Issue by mkastler** [MooveAgency/Post-Protection-and-Registration-Wall#7]
Not sure if this is specific to  WP 4.9.4 as I haven't attempted to drill down into the issue yet, but the error I receive when activating the plugin is this:

`Fatal error: Uncaught ArgumentCountError: Too few arguments to function Moove_View::load(), 1 passed in /www/wp-content/plugins/Post-Protection-and-Registration-Wall-master/moove-custom.php on line 138 and exactly 2 expected in /www/wp-content/plugins/Post-Protection-and-Registration-Wall-master/moove-view.php:27 Stack trace: #0 /www/wp-content/plugins/Post-Protection-and-Registration-Wall-master/moove-custom.php(138): Moove_View::load('moove.mail.remi...') #1 /www/wp-includes/class-wp-hook.php(286): moove_activate('') #2 /www/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters('', Array) #3 /www/wp-includes/plugin.php(453): WP_Hook->do_action(Array) #4 /www/wp-admin/plugins.php(174): do_action('activate_Post-P...') #5 {main} thrown in /www/wp-content/plugins/Post-Protection-and-Registration-Wall-master/moove-view.php on line 27`

**Comment by NemesGaspar** [comment]
Hi mkastler, 

Thanks for using our plugins. 
Please update the plugin to the latest version from the WordPress.org repository, or download from GitHub. 

Does the plugin work for you? I would love to hear your opinion on this, please rate our plugin in the WordPress.org repository with 5 stars.
https://wordpress.org/plugins/post-protection-and-registration-wall/

Looking forward to hearing your feedback.

Gaspar
